name: Diff Triggers
description: Check if changed files match trigger paths. Returns true if any trigger matches, false otherwise. Always returns true if triggers are omitted.
branding:
  icon: package
  color: blue

inputs:
  ### Required
  # Nothing!

  ### Typical / recommended
  triggers:
    description: Paths used to trigger an event; e.g. ('./backend/' './frontend/); always trigger if omitted

  ### Usually a bad idea / not recommended
  ref:
    description: Reference to compare against (e.g., 'main', 'HEAD^', commit SHA). Defaults to base repo default branch for PRs, or HEAD^ for non-PR events. Local refs (HEAD^, HEAD~2) work for non-PR events; remote refs (branches, tags, SHAs) work for all events
    required: false

outputs:
  triggered:
    description: Boolean result of triggers
    value: ${{ steps.diff.outputs.triggered }}

runs:
  using: composite
  steps:
    # Checkout appropriate ref based on event type
    - uses: actions/checkout@v6
      with:
        repository: ${{ github.event.pull_request.head.repo.full_name || github.repository }}
        ref: ${{ github.event.pull_request.head.sha || github.ref }}
        # Fetch all commits for non-PR events (defaults to 1 for PRs)
        fetch-depth: ${{ github.event.pull_request && 1 || 0 }}

    - shell: bash
      id: diff
      run: |
        # Diff for changes
        set -e
        CALLER_CONTEXT="[${{ github.workflow }} / ${{ github.job }}]"

        # Always fire if triggers are omitted
        if [ -z "${{ inputs.triggers }}" ]; then
          echo "::group::Diff Triggers — ✅ TRIGGERED | ${{ github.repository }} $CALLER_CONTEXT"
          echo "  Triggers: (omitted — always fires)"
          echo "::endgroup::"
          echo "::notice title=Diff Triggers::✅ Diff Triggers fired. (${{ github.repository }})"
          echo "triggered=true" >> $GITHUB_OUTPUT
          exit 0
        fi

        # Build if changed files (git diff) match triggers
        # Parse triggers input into array (properly handles quoted strings with spaces)
        TRIGGERS_STR="${{ inputs.triggers }}"
        # Extract all quoted strings preserving spaces within quotes
        TRIGGERS=()
        while IFS= read -r line; do
          [[ -n "$line" ]] && TRIGGERS+=("$line")
        done < <(grep -o "'[^']*'" <<< "$TRIGGERS_STR" | sed "s/'//g")

        # Determine reference to compare against
        # PR events: default to base repo default branch if ref omitted
        # Non-PR events: default to HEAD^ if ref omitted
        BASE_REF="${{ inputs.ref || github.event.pull_request.base.repo.default_branch || 'HEAD^' }}"
        if [ -n "${{ inputs.ref }}" ]; then
          REF_SOURCE="input"
        else
          REF_SOURCE="default"
        fi

        BASE_REMOTE_URL="${{ github.event.pull_request.base.repo.clone_url || github.event.repository.clone_url }}"
        if git remote get-url base >/dev/null 2>&1; then
          git remote set-url base "$BASE_REMOTE_URL"
        else
          git remote add base "$BASE_REMOTE_URL"
        fi
        
        # If BASE_REF starts with HEAD, it's a local ref - use it directly
        # Otherwise, fetch from remote and prefix
        if [[ "$BASE_REF" == HEAD* ]]; then
          COMPARE_REF="$BASE_REF"
        else
          git fetch base "$BASE_REF"
          COMPARE_REF="base/$BASE_REF"
        fi

        # Check all triggers and collect results
        TRIGGERED=false
        MATCHED_TRIGGERS=()
        DETAILS_LOG=""

        for t in "${TRIGGERS[@]}"; do
          DIFF_OUTPUT=$(git diff "$COMPARE_REF" --name-only -- "$t")
          if [[ -n "$DIFF_OUTPUT" ]]; then
            TRIGGERED=true
            MATCHED_TRIGGERS+=("$t")
            DETAILS_LOG+="  ✔ '$t'"$'\n'
            while IFS= read -r f; do
              DETAILS_LOG+="      $f"$'\n'
            done <<< "$DIFF_OUTPUT"
          else
            DETAILS_LOG+="  ✘ '$t'"$'\n'
          fi
        done

        # Single collapsible group — result in the title, details inside
        if [[ "$TRIGGERED" == "true" ]]; then
          MATCHED_LIST=$(IFS=', '; echo "${MATCHED_TRIGGERS[*]}")
          echo "::group::Diff Triggers — ✅ TRIGGERED | ${{ github.repository }} $CALLER_CONTEXT"
          echo "  Triggers:     $TRIGGERS_STR"
          echo "  Comparing to: $COMPARE_REF"
          echo "  Ref source:   $REF_SOURCE"
          echo "  Matched:      $MATCHED_LIST"
          echo ""
          echo "$DETAILS_LOG"
          echo "::endgroup::"
          echo "::notice title=Diff Triggers::✅ Diff Triggers fired. (${{ github.repository }})"
          echo "triggered=true" >> $GITHUB_OUTPUT
        else
          echo "::group::Diff Triggers — ⊘ NOT TRIGGERED | ${{ github.repository }} $CALLER_CONTEXT"
          echo "  Triggers:     $TRIGGERS_STR"
          echo "  Comparing to: $COMPARE_REF"
          echo "  Ref source:   $REF_SOURCE"
          echo ""
          echo "$DETAILS_LOG"
          echo "::endgroup::"
          echo "::notice title=Diff Triggers::⊘ Diff Triggers not fired. (${{ github.repository }})"
          echo "triggered=false" >> $GITHUB_OUTPUT
        fi
