name: Check Changed Files Against Triggers
description: Do changes match triggers? Supports PR, push, workflow_dispatch, and other events. Always trigger if triggers are omitted.
branding:
  icon: package
  color: blue

inputs:
  ### Required
  # Nothing!

  ### Typical / recommended
  triggers:
    description: Paths used to trigger an event; e.g. ('./backend/' './frontend/); always trigger if omitted

  ### Usually a bad idea / not recommended
  base_ref:
    description: Base reference to compare against (e.g., 'main', 'HEAD^', commit SHA). Defaults to base repo default branch for PRs, or HEAD^ for non-PR events
    required: false
  
  diff_branch:
    description: Deprecated: use base_ref instead. For backward compatibility, if provided, used as base_ref for PR events
    required: false

  head_ref:
    description: Head reference to checkout (the code to compare). Defaults to PR head SHA for PRs, or current ref for non-PR events
    required: false

outputs:
  triggered:
    description: Boolean result of triggers
    value: ${{ steps.diff.outputs.triggered }}

runs:
  using: composite
  steps:
    # Checkout appropriate ref based on event type
    - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6
      with:
        repository: ${{ github.event.pull_request.head.repo.full_name || github.repository }}
        ref: ${{ inputs.head_ref || github.event.pull_request.head.sha || github.ref }}

    - shell: bash
      id: diff
      run: |
        # Diff for changes
        set -e

        # Always fire if triggers are omitted
        if [ -z "${{ inputs.triggers }}" ]; then
          echo "Always fire when triggers are omitted!"
          echo "triggered=true" >> $GITHUB_OUTPUT
          exit 0
        fi

        # Build if changed files (git diff) match triggers
        # Parse triggers input into array (properly handles quoted strings with spaces)
        TRIGGERS_STR="${{ inputs.triggers }}"
        # Extract all quoted strings preserving spaces within quotes
        TRIGGERS=()
        while IFS= read -r line; do
          [[ -n "$line" ]] && TRIGGERS+=("$line")
        done < <(grep -o "'[^']*'" <<< "$TRIGGERS_STR" | sed "s/'//g")

        # Determine base reference (what to compare against)
        # Support diff_branch for backward compatibility (workflow_dispatch triggered from PRs)
        if [ -n "${{ inputs.base_ref }}" ]; then
          # User provided base_ref
          BASE_REF="${{ inputs.base_ref }}"
        elif [ -n "${{ inputs.diff_branch }}" ]; then
          # Backward compatibility: diff_branch provided
          BASE_REF="${{ inputs.diff_branch }}"
          # For PR events, fetch from base repo; for workflow_dispatch, use local branch
          if [ "${{ github.event_name }}" == "pull_request" ] || [ "${{ github.event_name }}" == "pull_request_target" ]; then
            git remote add to_diff "${{ github.event.pull_request.base.repo.clone_url }}"
            git fetch to_diff "$BASE_REF"
            BASE_REF="to_diff/$BASE_REF"
          fi
        elif [ "${{ github.event_name }}" == "pull_request" ] || [ "${{ github.event_name }}" == "pull_request_target" ]; then
          # PR event: use base repo default branch
          BASE_REF="${{ github.event.pull_request.base.repo.default_branch }}"
          git remote add to_diff "${{ github.event.pull_request.base.repo.clone_url }}"
          git fetch to_diff "$BASE_REF"
          BASE_REF="to_diff/$BASE_REF"
        else
          # Non-PR event: default to HEAD^ (previous commit)
          BASE_REF="HEAD^"
        fi

        # Check if any changed file matches any trigger using git diff's pathspec matching
        for t in "${TRIGGERS[@]}"; do
          if git diff "$BASE_REF" --name-only -- "$t" | grep -q .; then
            echo "Build triggered based on git diff"
            echo "triggered=true" >> $GITHUB_OUTPUT
            exit 0
          fi
        done

        # If at this point, no trigger has fired
        echo "Triggers have not fired"
        echo "triggered=false" >> $GITHUB_OUTPUT
