name: Check Changed Files Against Triggers
description: Do changes match triggers?  Always trigger if triggers are omitted.
branding:
  icon: package
  color: blue

inputs:
  ### Required
  # Nothing!

  ### Typical / recommended
  triggers:
    description: Paths used to trigger an event; e.g. ('./backend/' './frontend/); always trigger if omitted

  ### Usually a bad idea / not recommended
  diff_branch:
    description: Branch to diff against, defaults to the default branch
    default: ${{ github.event.pull_request.base.repo.default_branch }}

outputs:
  triggered:
    description: Boolean result of triggers
    value: ${{ steps.diff.outputs.triggered }}

runs:
  using: composite
  steps:
    # Checkout PR head (works for both fork and non-fork PRs; requires pull_request or pull_request_target)
    - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6
      with:
        repository: ${{ github.event.pull_request.head.repo.full_name }}
        ref: ${{ github.event.pull_request.head.sha }}

    - shell: bash
      id: diff
      run: |
        # Diff for changes
        set -e

        # Always fire if triggers are omitted
        if [ -z "${{ inputs.triggers }}" ]; then
          echo "Always fire when triggers are omitted!"
          echo "triggered=true" >> $GITHUB_OUTPUT
          exit 0
        fi

        # Build if changed files (git diff) match triggers
        # Parse triggers input into array (properly handles quoted strings with spaces)
        TRIGGERS_STR="${{ inputs.triggers }}"
        # Extract all quoted strings preserving spaces within quotes
        TRIGGERS=()
        while IFS= read -r line; do
          [[ -n "$line" ]] && TRIGGERS+=("$line")
        done < <(grep -o "'[^']*'" <<< "$TRIGGERS_STR" | sed "s/'//g")

        # Add remote and fetch branch (treats forks and non-forks the same)
        git remote add to_diff "${{ github.event.pull_request.base.repo.clone_url }}"
        git fetch to_diff ${{ inputs.diff_branch }}

        # Build grep pattern: directories use prefix match, files use exact match
        GREP_PATTERNS=()
        for t in "${TRIGGERS[@]}"; do
          # Escape special regex characters
          escaped_t=$(printf '%s\n' "$t" | sed 's/[[\.*^$()+?{|]/\\&/g')
          if [[ "$t" == */ ]]; then
            # Directory: prefix match (e.g., '^\./backend/')
            GREP_PATTERNS+=("^$escaped_t")
          else
            # File: match at start or after any path, at end (e.g., '(^|.*/)action\.yml$')
            # This matches 'action.yml', './action.yml', or 'path/to/action.yml' but not 'action.yml.backup'
            GREP_PATTERNS+=("(^|.*/)$escaped_t$")
          fi
        done
        # Join patterns with |
        GREP_PATTERN=$(IFS='|'; echo "${GREP_PATTERNS[*]}")

        # Check if any changed file matches any trigger
        if git diff "to_diff/${{ inputs.diff_branch }}" --name-only | grep -qE "$GREP_PATTERN"; then
          echo "Build triggered based on git diff"
          echo "triggered=true" >> $GITHUB_OUTPUT
          exit 0
        fi

        # If at this point, no trigger has fired
        echo "Triggers have not fired"
        echo "triggered=false" >> $GITHUB_OUTPUT
