name: Conditional Container Builder with Fallback
description: Build if trigger conditions are met, else use fallback image
branding:
  icon: package
  color: blue

inputs:
  ### Required
  # Nothing!

  ### Typical / recommended
  triggers:
    description: Paths used to trigger an event; e.g. ('./backend/' './frontend/); always trigger if omitted

  ### Usually a bad idea / not recommended
  diff_branch:
    description: Branch to diff against, defaults to the default branch
    default: ${{ github.event.repository.default_branch }}

outputs:
  triggered:
    description: Boolean result of triggers
    value: ${{ steps.diff.outputs.triggered }}

runs:
  using: composite
  steps:
    # Detect fork PRs and set checkout/diff variables
    - name: Vars and fork handling
      shell: bash
      id: fork
      run: |
        # Check if this is a fork PR (head repo != base repo)
        if [ "${{ github.event.pull_request.head.repo.full_name }}" != "${{ github.repository }}" ]; then
          # Fork PR: fetch from base remote
          echo "remote=base" >> $GITHUB_OUTPUT
          echo "clone_url=${{ github.event.repository.clone_url }}" >> $GITHUB_OUTPUT
        else
          # Non-fork: fetch from origin
          echo "remote=origin" >> $GITHUB_OUTPUT
        fi

    # Checkout the determined repository at the determined ref
    - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6
      with:
        repository: ${{ github.event.pull_request.head.repo.full_name }}
        ref: ${{ github.event.pull_request.head.sha }}

    - name: Diff for changes
      shell: bash
      id: diff
      run: |
        # Always fire if triggers are omitted
        if [ -z "${{ inputs.triggers }}" ]; then
          echo "Always fire when triggers are omitted!"
          echo "triggered=true" >> $GITHUB_OUTPUT
          exit 0
        fi

        # Build if changed files (git diff) match triggers
        TRIGGERS=${{ inputs.triggers }}

        # Fetch diff_branch for comparison
        # For forks: set up base remote (clone_url only exists for forks)
        if [ -n "${{ steps.fork.outputs.clone_url }}" ]; then
          git remote add ${{ steps.fork.outputs.remote }} ${{ steps.fork.outputs.clone_url }}
        fi
        git fetch ${{ steps.fork.outputs.remote }} ${{ inputs.diff_branch }}

        while read -r check; do
          for t in "${TRIGGERS[@]}"; do
            if [[ "${check}" =~ "${t}" ]]; then
                # Output triggered=true for next steps
                echo "Build triggered based on git diff"
                echo -e "${t}\n --> ${check}"
                echo "triggered=true" >> $GITHUB_OUTPUT
                exit 0
            fi
          done
        done < <(git diff "${{ steps.fork.outputs.remote }}/${{ inputs.diff_branch }}" --name-only)

        # If at this point, no trigger has fired
        echo "Triggers have not fired"
        echo "triggered=false" >> $GITHUB_OUTPUT
