name: Diff Triggers
description: Check if changed files match trigger paths. Returns true if any trigger matches, false otherwise. Always returns true if triggers are omitted.
branding:
  icon: package
  color: blue

inputs:
  ### Required
  # Nothing!

  ### Typical / recommended
  triggers:
    description: Paths used to trigger an event; e.g. ('./backend/' './frontend/); always trigger if omitted

  ### Usually a bad idea / not recommended
  ref:
    description: Reference to compare against (e.g., 'main', 'HEAD^', commit SHA). Defaults to base repo default branch for PRs, or HEAD^ for non-PR events
    required: false

outputs:
  triggered:
    description: Boolean result of triggers
    value: ${{ steps.diff.outputs.triggered }}

runs:
  using: composite
  steps:
    # Checkout appropriate ref based on event type
    - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6
      with:
        repository: ${{ github.event.pull_request.head.repo.full_name || github.repository }}
        ref: ${{ github.event.pull_request.head.sha || github.ref }}
        # Fetch all commits for non-PR events (defaults to 1 for PRs)
        fetch-depth: ${{ github.event.pull_request && 1 || 0 }}

    - shell: bash
      id: diff
      run: |
        # Diff for changes
        set -e

        # Always fire if triggers are omitted
        if [ -z "${{ inputs.triggers }}" ]; then
          echo "Always fire when triggers are omitted!"
          echo "triggered=true" >> $GITHUB_OUTPUT
          exit 0
        fi

        # Build if changed files (git diff) match triggers
        # Parse triggers input into array (properly handles quoted strings with spaces)
        TRIGGERS_STR="${{ inputs.triggers }}"
        # Extract all quoted strings preserving spaces within quotes
        TRIGGERS=()
        while IFS= read -r line; do
          [[ -n "$line" ]] && TRIGGERS+=("$line")
        done < <(grep -o "'[^']*'" <<< "$TRIGGERS_STR" | sed "s/'//g")

        # Determine reference to compare against (works for all events)
        COMPARE_REF="${{ inputs.ref || github.event.pull_request.base.repo.default_branch || 'HEAD^' }}"
        
        # For PR events, fetch from base repo and prefix
        if [ "${{ github.event_name }}" == "pull_request" ] || [ "${{ github.event_name }}" == "pull_request_target" ]; then
          git remote add base "${{ github.event.pull_request.base.repo.clone_url }}"
          git fetch base "$COMPARE_REF"
          COMPARE_REF="base/$COMPARE_REF"
        fi

        # Check if any changed file matches any trigger using git diff's pathspec matching
        for t in "${TRIGGERS[@]}"; do
          if git diff "$COMPARE_REF" --name-only -- "$t" | grep -q .; then
            echo "Build triggered based on git diff"
            echo "triggered=true" >> $GITHUB_OUTPUT
            exit 0
          fi
        done

        # If at this point, no trigger has fired
        echo "Triggers have not fired"
        echo "triggered=false" >> $GITHUB_OUTPUT
