name: Conditional Container Builder with Fallback
description: Build if trigger conditions are met, else use fallback image
branding:
  icon: package
  color: blue

inputs:
  ### Required
  # Nothing!

  ### Typical / recommended
  triggers:
    description: Paths used to trigger an event; e.g. ('./backend/' './frontend/); always trigger if omitted

  ### Usually a bad idea / not recommended
  diff_branch:
    description: Branch to diff against, defaults to the default branch
    default: ${{ github.event.repository.default_branch }}

outputs:
  triggered:
    description: Boolean result of triggers
    value: ${{ steps.diff.outputs.triggered }}

runs:
  using: composite
  steps:
    # Detect fork PRs and set checkout/diff variables
    # For fork PRs in pull_request_target context: checkout fork repo, compare against base repo
    # For non-fork PRs: checkout base repo, compare against base repo's diff_branch
    - name: Vars and fork handling
      shell: bash
      id: fork
      run: |
        # Check if this is a fork PR in pull_request_target context
        if [ "${{ github.event_name }}" = "pull_request_target" ] && [ "${{ github.event.pull_request.head.repo.full_name }}" != "${{ github.repository }}" ]; then
          # Fork PR: checkout fork repo, compare against base repo
          echo "repository=${{ github.event.pull_request.head.repo.full_name }}" >> $GITHUB_OUTPUT
          echo "ref=${{ github.event.pull_request.head.sha }}" >> $GITHUB_OUTPUT
          echo "is_fork=true" >> $GITHUB_OUTPUT
          echo "base_repo_url=${{ github.event.repository.clone_url }}" >> $GITHUB_OUTPUT
          echo "diff_ref=base/${{ inputs.diff_branch }}" >> $GITHUB_OUTPUT
        else
          # Non-fork: checkout base repo
          echo "repository=${{ github.repository }}" >> $GITHUB_OUTPUT
          echo "ref=${{ github.ref }}" >> $GITHUB_OUTPUT
          echo "is_fork=false" >> $GITHUB_OUTPUT
          echo "diff_ref=origin/${{ inputs.diff_branch }}" >> $GITHUB_OUTPUT
        fi

    # Checkout the determined repository at the determined ref
    - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6
      with:
        repository: ${{ steps.fork.outputs.repository }}
        ref: ${{ steps.fork.outputs.ref }}

    - name: Diff for changes
      shell: bash
      id: diff
      run: |
        # Always fire if triggers are omitted
        if [ -z "${{ inputs.triggers }}" ]; then
          echo "Always fire when triggers are omitted!"
          echo "triggered=true" >> $GITHUB_OUTPUT
          exit 0
        fi

        # Build if changed files (git diff) match triggers
        TRIGGERS=${{ inputs.triggers }}

        # Fetch base repo's diff_branch for comparison (DIFF_REF determined in first step)
        if [ "${{ steps.fork.outputs.is_fork }}" = "true" ]; then
          git remote set-url base ${{ steps.fork.outputs.base_repo_url }} 2>/dev/null || git remote add base ${{ steps.fork.outputs.base_repo_url }}
          git fetch base ${{ inputs.diff_branch }}
        else
          git fetch origin ${{ inputs.diff_branch }}
        fi
        DIFF_REF="${{ steps.fork.outputs.diff_ref }}"

        while read -r check; do
          for t in "${TRIGGERS[@]}"; do
            if [[ "${check}" =~ "${t}" ]]; then
                # Output triggered=true for next steps
                echo "Build triggered based on git diff"
                echo -e "${t}\n --> ${check}"
                echo "triggered=true" >> $GITHUB_OUTPUT
                exit 0
            fi
          done
        done < <(git diff "$DIFF_REF" --name-only)

        # If at this point, no trigger has fired
        echo "Triggers have not fired"
        echo "triggered=false" >> $GITHUB_OUTPUT
