name: Check Changed Files Against Triggers
description: Do changes match triggers?  Always trigger if triggers are omitted.
branding:
  icon: package
  color: blue

inputs:
  ### Required
  # Nothing!

  ### Typical / recommended
  triggers:
    description: Paths used to trigger an event; e.g. ('./backend/' './frontend/); always trigger if omitted

  ### Usually a bad idea / not recommended
  diff_branch:
    description: Branch to diff against, defaults to the default branch
    default: ${{ github.event.repository.default_branch }}

outputs:
  triggered:
    description: Boolean result of triggers
    value: ${{ steps.diff.outputs.triggered }}

runs:
  using: composite
  steps:
    # Checkout PR head (works for both fork and non-fork PRs; requires pull_request or pull_request_target)
    - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6
      with:
        repository: ${{ github.event.pull_request.head.repo.full_name }}
        ref: ${{ github.event.pull_request.head.sha }}

    - shell: bash
      id: diff
      run: |
        # Diff for changes
        set -e

        # Always fire if triggers are omitted
        if [ -z "${{ inputs.triggers }}" ]; then
          echo "Always fire when triggers are omitted!"
          echo "triggered=true" >> $GITHUB_OUTPUT
          exit 0
        fi

        # Build if changed files (git diff) match triggers
        TRIGGERS=${{ inputs.triggers }}

        # Add remote and fetch branch (treats forks and non-forks the same)
        git remote add to_diff "${{ github.event.repository.clone_url }}"
        git fetch to_diff ${{ inputs.diff_branch }}

        # Use three-dot diff to show only PR changes (finds merge-base automatically)
        BASE_SHA=$(git merge-base HEAD "to_diff/${{ inputs.diff_branch }}")
        while read -r check; do
          for t in "${TRIGGERS[@]}"; do
            if [[ "${check}" =~ "${t}" ]]; then
                # Output triggered=true for next steps
                echo "Build triggered based on git diff"
                echo -e "${t}\n --> ${check}"
                echo "triggered=true" >> $GITHUB_OUTPUT
                exit 0
            fi
          done
        done < <(git diff "$BASE_SHA" --name-only)

        # If at this point, no trigger has fired
        echo "Triggers have not fired"
        echo "triggered=false" >> $GITHUB_OUTPUT
